# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Mãe Realista"
description: > # this means to ignore newlines until "email:"
        Mãe de primeira viagem que tem como hobbies ler e escrever, e um belo
        dia acordou com vontade de desconstruir e controverter.

email: ritasamaele@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Rita Samaele'
author: 'Rita Samaele'
author_image: "/assets/images/author.png"

paginate: 5

url: "http://www.maerealista.com"
baseurl: ""
#used to display twitter cards
twitter_handle: '@ritasamaele'

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/ritasamaele
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url: https://facebook.com/maerealistablog
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
