# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Mãe Realista"
description: > # this means to ignore newlines until "email:"
        Mãe de primeira viagem que tem como hobbies ler e escrever, e um belo
        dia acordou com vontade de desconstruir e polemizar.

email: maerealista.com@gmail.com
#blog logo
#logo: "/assets/images/logo.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Rita Samaele'
author: 'Rita Samaele'
author_image: "/assets/images/author.png"

paginate: 5

url: "http://www.maerealista.com"
baseurl: ""
#used to display twitter cards
twitter_handle: '@maerealista'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/maerealista
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url: https://facebook.com/blogmaerealista
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
